[project]
name = "bitcoin-dev-academy-contracts"
description = "Smart contracts for Bitcoin Developer Academy"
authors = ["Bitcoin Developer Academy"]
telemetry = false
cache_dir = "./.clarinet"

[contracts.certificate-nft]
path = "contracts/certificate-nft.clar"
clarity_version = 2
epoch = 2.4

[contracts.progress-tracker]
path = "contracts/progress-tracker.clar"
clarity_version = 2
epoch = 2.4



[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
